// <auto-generated>
//     Generated by scripts/gen-strings.ps1 from Strings.resx (ADR-064).
//     Do not edit by hand — add the key to Strings.resx and rerun the script.
// </auto-generated>

// The <auto-generated> header above opts this file out of the project's implicit
// nullable context, so the annotations below need it back explicitly (CS8669).
#nullable enable

namespace Parlotype.Desktop.Resources;

/// <summary>
/// Strongly-typed accessor for <c>Strings.resx</c> — the app's externalized
/// user-facing copy (ADR-056, ADR-064). Each property reads at the current
/// interface language, so a value captured before a language switch is stale;
/// bind through <see cref="Localizer.Entry"/> (or <c>{loc:Tr}</c> in markup) for
/// text that stays on screen. A missing key falls back to the key name so a stale
/// resx never crashes the UI. Public so tests can verify every key resolves
/// (Desktop has no InternalsVisibleTo for the test project's benefit here).
/// </summary>
public static class Strings
{
    /// <summary>Show / hide key</summary>
    public static string ApiKeyBox_ShowHideTooltip => Localizer.Lookup(nameof(ApiKeyBox_ShowHideTooltip));

    /// <summary>not a valid absolute URL</summary>
    public static string Cloud_BaseUrl_NotAbsolute => Localizer.Lookup(nameof(Cloud_BaseUrl_NotAbsolute));

    /// <summary>plain http is only allowed for localhost — the API key and audio would leave this machine unencrypted</summary>
    public static string Cloud_BaseUrl_PlainHttp => Localizer.Lookup(nameof(Cloud_BaseUrl_PlainHttp));

    /// <summary>unsupported scheme '{0}' — use https</summary>
    public static string Cloud_BaseUrl_UnsupportedSchemeFormat => Localizer.Lookup(nameof(Cloud_BaseUrl_UnsupportedSchemeFormat));
    /// <summary>unsupported scheme '{0}' — use https</summary>
    public static string Format_Cloud_BaseUrl_UnsupportedSchemeFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Cloud_BaseUrl_UnsupportedSchemeFormat, arg0);

    /// <summary>{0}: the API key was rejected (HTTP {1}). {2} Check the key in Settings → Speech engine.</summary>
    public static string Cloud_Error_KeyRejectedFormat => Localizer.Lookup(nameof(Cloud_Error_KeyRejectedFormat));
    /// <summary>{0}: the API key was rejected (HTTP {1}). {2} Check the key in Settings → Speech engine.</summary>
    public static string Format_Cloud_Error_KeyRejectedFormat(object? arg0, object? arg1, object? arg2) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Cloud_Error_KeyRejectedFormat, arg0, arg1, arg2);

    /// <summary>{0}: transcription failed (HTTP {1}). {2}</summary>
    public static string Cloud_Error_OtherFormat => Localizer.Lookup(nameof(Cloud_Error_OtherFormat));
    /// <summary>{0}: transcription failed (HTTP {1}). {2}</summary>
    public static string Format_Cloud_Error_OtherFormat(object? arg0, object? arg1, object? arg2) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Cloud_Error_OtherFormat, arg0, arg1, arg2);

    /// <summary>{0} is unavailable right now (HTTP {1}) — try again shortly. ({2})</summary>
    public static string Cloud_Error_ProviderUnavailableFormat => Localizer.Lookup(nameof(Cloud_Error_ProviderUnavailableFormat));
    /// <summary>{0} is unavailable right now (HTTP {1}) — try again shortly. ({2})</summary>
    public static string Format_Cloud_Error_ProviderUnavailableFormat(object? arg0, object? arg1, object? arg2) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Cloud_Error_ProviderUnavailableFormat, arg0, arg1, arg2);

    /// <summary>{0}: API quota exceeded — check your plan and billing with the provider. ({1})</summary>
    public static string Cloud_Error_QuotaExceededFormat => Localizer.Lookup(nameof(Cloud_Error_QuotaExceededFormat));
    /// <summary>{0}: API quota exceeded — check your plan and billing with the provider. ({1})</summary>
    public static string Format_Cloud_Error_QuotaExceededFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Cloud_Error_QuotaExceededFormat, arg0, arg1);

    /// <summary>{0}: rate limit reached — wait a moment and try again. ({1})</summary>
    public static string Cloud_Error_RateLimitedFormat => Localizer.Lookup(nameof(Cloud_Error_RateLimitedFormat));
    /// <summary>{0}: rate limit reached — wait a moment and try again. ({1})</summary>
    public static string Format_Cloud_Error_RateLimitedFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Cloud_Error_RateLimitedFormat, arg0, arg1);

    /// <summary>{0}: the base URL is rejected ({1}). Fix it in Settings → Speech engine.</summary>
    public static string Cloud_NotConfigured_InvalidBaseUrlFormat => Localizer.Lookup(nameof(Cloud_NotConfigured_InvalidBaseUrlFormat));
    /// <summary>{0}: the base URL is rejected ({1}). Fix it in Settings → Speech engine.</summary>
    public static string Format_Cloud_NotConfigured_InvalidBaseUrlFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Cloud_NotConfigured_InvalidBaseUrlFormat, arg0, arg1);

    /// <summary>{0}: no API key configured. Add one in Settings → Speech engine.</summary>
    public static string Cloud_NotConfigured_MissingKeyFormat => Localizer.Lookup(nameof(Cloud_NotConfigured_MissingKeyFormat));
    /// <summary>{0}: no API key configured. Add one in Settings → Speech engine.</summary>
    public static string Format_Cloud_NotConfigured_MissingKeyFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Cloud_NotConfigured_MissingKeyFormat, arg0);

    /// <summary>OpenAI-compatible provider</summary>
    public static string Cloud_ProviderName_OpenAiCompatible => Localizer.Lookup(nameof(Cloud_ProviderName_OpenAiCompatible));

    /// <summary>xAI Grok</summary>
    public static string Cloud_ProviderName_XaiGrok => Localizer.Lookup(nameof(Cloud_ProviderName_XaiGrok));

    /// <summary>Cancel</summary>
    public static string Common_Cancel => Localizer.Lookup(nameof(Common_Cancel));

    /// <summary>Close</summary>
    public static string Common_Close => Localizer.Lookup(nameof(Common_Close));

    /// <summary>OK</summary>
    public static string Common_Ok => Localizer.Lookup(nameof(Common_Ok));

    /// <summary>Open settings</summary>
    public static string Common_OpenSettings => Localizer.Lookup(nameof(Common_OpenSettings));

    /// <summary>Cloud provider not configured</summary>
    public static string Dialog_CloudNotConfigured_Title => Localizer.Lookup(nameof(Dialog_CloudNotConfigured_Title));

    /// <summary>Cloud transcription failed</summary>
    public static string Dialog_CloudTranscriptionFailed_Title => Localizer.Lookup(nameof(Dialog_CloudTranscriptionFailed_Title));

    /// <summary>Esc — cancel the current recording</summary>
    public static string Help_EscCancelLine => Localizer.Lookup(nameof(Help_EscCancelLine));

    /// <summary>Current dictation hotkeys</summary>
    public static string Help_HotkeysHeading => Localizer.Lookup(nameof(Help_HotkeysHeading));

    /// <summary>New to Parlotype? The guided tour walks through recording, the widget, engines and models — opening each screen and h...</summary>
    public static string Help_Intro => Localizer.Lookup(nameof(Help_Intro));

    /// <summary>No dictation hotkeys are configured. Add one in the Hotkeys section.</summary>
    public static string Help_NoHotkeys => Localizer.Lookup(nameof(Help_NoHotkeys));

    /// <summary>Open the tour</summary>
    public static string Help_OpenTourButton => Localizer.Lookup(nameof(Help_OpenTourButton));

    /// <summary>Help</summary>
    public static string Help_Title => Localizer.Lookup(nameof(Help_Title));

    /// <summary>{0} to dictate</summary>
    public static string Hotkey_Hint_DictateFormat => Localizer.Lookup(nameof(Hotkey_Hint_DictateFormat));
    /// <summary>{0} to dictate</summary>
    public static string Format_Hotkey_Hint_DictateFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Hotkey_Hint_DictateFormat, arg0);

    /// <summary>No dictation hotkey set</summary>
    public static string Hotkey_Hint_None => Localizer.Lookup(nameof(Hotkey_Hint_None));

    /// <summary>{0} to talk</summary>
    public static string Hotkey_Hint_TalkFormat => Localizer.Lookup(nameof(Hotkey_Hint_TalkFormat));
    /// <summary>{0} to talk</summary>
    public static string Format_Hotkey_Hint_TalkFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Hotkey_Hint_TalkFormat, arg0);

    /// <summary>{0} · Esc to cancel</summary>
    public static string Hotkey_Hint_WithCancelFormat => Localizer.Lookup(nameof(Hotkey_Hint_WithCancelFormat));
    /// <summary>{0} · Esc to cancel</summary>
    public static string Format_Hotkey_Hint_WithCancelFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Hotkey_Hint_WithCancelFormat, arg0);

    /// <summary>Choose a model that translates</summary>
    public static string Language_ChooseTranslatingModel => Localizer.Lookup(nameof(Language_ChooseTranslatingModel));

    /// <summary>Translation paused — "{0}" can't translate</summary>
    public static string Language_Connector_PausedTooltipFormat => Localizer.Lookup(nameof(Language_Connector_PausedTooltipFormat));
    /// <summary>Translation paused — "{0}" can't translate</summary>
    public static string Format_Language_Connector_PausedTooltipFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_Connector_PausedTooltipFormat, arg0);

    /// <summary>Turn translation off</summary>
    public static string Language_Connector_TurnOffTooltip => Localizer.Lookup(nameof(Language_Connector_TurnOffTooltip));

    /// <summary>Turn translation on</summary>
    public static string Language_Connector_TurnOnTooltip => Localizer.Lookup(nameof(Language_Connector_TurnOnTooltip));

    /// <summary>All languages</summary>
    public static string Language_Picker_AllLanguagesGroup => Localizer.Lookup(nameof(Language_Picker_AllLanguagesGroup));

    /// <summary>No languages match "{0}".</summary>
    public static string Language_Picker_NoResultsFormat => Localizer.Lookup(nameof(Language_Picker_NoResultsFormat));
    /// <summary>No languages match "{0}".</summary>
    public static string Format_Language_Picker_NoResultsFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_Picker_NoResultsFormat, arg0);

    /// <summary>Recent</summary>
    public static string Language_Picker_RecentGroup => Localizer.Lookup(nameof(Language_Picker_RecentGroup));

    /// <summary>Search languages…</summary>
    public static string Language_Picker_SearchPlaceholder => Localizer.Lookup(nameof(Language_Picker_SearchPlaceholder));

    /// <summary>Auto-detect</summary>
    public static string Language_Source_AutoDetect => Localizer.Lookup(nameof(Language_Source_AutoDetect));

    /// <summary>Let the model identify the language</summary>
    public static string Language_Source_AutoDetectHint => Localizer.Lookup(nameof(Language_Source_AutoDetectHint));

    /// <summary>Detected: {0}</summary>
    public static string Language_Source_DetectedFormat => Localizer.Lookup(nameof(Language_Source_DetectedFormat));
    /// <summary>Detected: {0}</summary>
    public static string Format_Language_Source_DetectedFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_Source_DetectedFormat, arg0);

    /// <summary>System keyboard layout</summary>
    public static string Language_Source_KeyboardLayout => Localizer.Lookup(nameof(Language_Source_KeyboardLayout));

    /// <summary>Layout detection unavailable — auto-detecting instead</summary>
    public static string Language_Source_LayoutUnavailable => Localizer.Lookup(nameof(Language_Source_LayoutUnavailable));

    /// <summary>Spoken language</summary>
    public static string Language_Source_SpokenLanguageHint => Localizer.Lookup(nameof(Language_Source_SpokenLanguageHint));

    /// <summary>any language</summary>
    public static string Language_Summary_AnyLanguage => Localizer.Lookup(nameof(Language_Summary_AnyLanguage));

    /// <summary>You speak {0} → Parlotype types {1}.</summary>
    public static string Language_Summary_Format => Localizer.Lookup(nameof(Language_Summary_Format));
    /// <summary>You speak {0} → Parlotype types {1}.</summary>
    public static string Format_Language_Summary_Format(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_Summary_Format, arg0, arg1);

    /// <summary>{0} (no translation)</summary>
    public static string Language_Summary_NoTranslationFormat => Localizer.Lookup(nameof(Language_Summary_NoTranslationFormat));
    /// <summary>{0} (no translation)</summary>
    public static string Format_Language_Summary_NoTranslationFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_Summary_NoTranslationFormat, arg0);

    /// <summary>{0} (translation paused)</summary>
    public static string Language_Summary_TranslationPausedFormat => Localizer.Lookup(nameof(Language_Summary_TranslationPausedFormat));
    /// <summary>{0} (translation paused)</summary>
    public static string Format_Language_Summary_TranslationPausedFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_Summary_TranslationPausedFormat, arg0);

    /// <summary>your keyboard language</summary>
    public static string Language_Summary_YourKeyboardLanguage => Localizer.Lookup(nameof(Language_Summary_YourKeyboardLanguage));

    /// <summary>Same as source</summary>
    public static string Language_Target_SameAsSource => Localizer.Lookup(nameof(Language_Target_SameAsSource));

    /// <summary>Translation target</summary>
    public static string Language_Target_TranslationHint => Localizer.Lookup(nameof(Language_Target_TranslationHint));

    /// <summary>{0} can't translate — output now matches your spoken language.</summary>
    public static string Language_Toast_EngineCannotTranslateFormat => Localizer.Lookup(nameof(Language_Toast_EngineCannotTranslateFormat));
    /// <summary>{0} can't translate — output now matches your spoken language.</summary>
    public static string Format_Language_Toast_EngineCannotTranslateFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_Toast_EngineCannotTranslateFormat, arg0);

    /// <summary>"{0}" can't translate — translation is paused until you pick a multilingual model.</summary>
    public static string Language_Toast_ModelPausedFormat => Localizer.Lookup(nameof(Language_Toast_ModelPausedFormat));
    /// <summary>"{0}" can't translate — translation is paused until you pick a multilingual model.</summary>
    public static string Format_Language_Toast_ModelPausedFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_Toast_ModelPausedFormat, arg0);

    /// <summary>{0} isn't a source in {1}. Using your keyboard layout.</summary>
    public static string Language_Toast_SourceUnsupportedFormat => Localizer.Lookup(nameof(Language_Toast_SourceUnsupportedFormat));
    /// <summary>{0} isn't a source in {1}. Using your keyboard layout.</summary>
    public static string Format_Language_Toast_SourceUnsupportedFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_Toast_SourceUnsupportedFormat, arg0, arg1);

    /// <summary>Previous target reset — not supported by {0}.</summary>
    public static string Language_Toast_TargetResetFormat => Localizer.Lookup(nameof(Language_Toast_TargetResetFormat));
    /// <summary>Previous target reset — not supported by {0}.</summary>
    public static string Format_Language_Toast_TargetResetFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_Toast_TargetResetFormat, arg0);

    /// <summary>{0} isn't available in {1}. Translation set to {2}.</summary>
    public static string Language_Toast_TargetUnsupportedFormat => Localizer.Lookup(nameof(Language_Toast_TargetUnsupportedFormat));
    /// <summary>{0} isn't available in {1}. Translation set to {2}.</summary>
    public static string Format_Language_Toast_TargetUnsupportedFormat(object? arg0, object? arg1, object? arg2) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_Toast_TargetUnsupportedFormat, arg0, arg1, arg2);

    /// <summary>Translate</summary>
    public static string Language_ToggleSwitch_Translate => Localizer.Lookup(nameof(Language_ToggleSwitch_Translate));

    /// <summary>Translate to {0}</summary>
    public static string Language_ToggleSwitch_TranslateToFormat => Localizer.Lookup(nameof(Language_ToggleSwitch_TranslateToFormat));
    /// <summary>Translate to {0}</summary>
    public static string Format_Language_ToggleSwitch_TranslateToFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_ToggleSwitch_TranslateToFormat, arg0);

    /// <summary>Translation is paused — "{0}" is transcription-only. Pick Medium or Large v1/v2/v3 to resume.</summary>
    public static string Language_TranslationPausedNoteFormat => Localizer.Lookup(nameof(Language_TranslationPausedNoteFormat));
    /// <summary>Translation is paused — "{0}" is transcription-only. Pick Medium or Large v1/v2/v3 to resume.</summary>
    public static string Format_Language_TranslationPausedNoteFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_TranslationPausedNoteFormat, arg0);

    /// <summary>{0} can't translate — Parlotype types exactly what you say.</summary>
    public static string Language_UnavailableNoteFormat => Localizer.Lookup(nameof(Language_UnavailableNoteFormat));
    /// <summary>{0} can't translate — Parlotype types exactly what you say.</summary>
    public static string Format_Language_UnavailableNoteFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Language_UnavailableNoteFormat, arg0);

    /// <summary>Download "{0}" ({1}) from the internet?</summary>
    public static string ModelDownload_ConfirmFormat => Localizer.Lookup(nameof(ModelDownload_ConfirmFormat));
    /// <summary>Download "{0}" ({1}) from the internet?</summary>
    public static string Format_ModelDownload_ConfirmFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, ModelDownload_ConfirmFormat, arg0, arg1);

    /// <summary>Download "{0}" ({1}, includes vision projector) from the internet?</summary>
    public static string ModelDownload_ConfirmWithProjectorFormat => Localizer.Lookup(nameof(ModelDownload_ConfirmWithProjectorFormat));
    /// <summary>Download "{0}" ({1}, includes vision projector) from the internet?</summary>
    public static string Format_ModelDownload_ConfirmWithProjectorFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, ModelDownload_ConfirmWithProjectorFormat, arg0, arg1);

    /// <summary>Download</summary>
    public static string ModelDownload_DownloadButton => Localizer.Lookup(nameof(ModelDownload_DownloadButton));

    /// <summary>Model Download</summary>
    public static string ModelDownload_Title => Localizer.Lookup(nameof(ModelDownload_Title));

    /// <summary>The two cloud engines are off by default and require your own API key. While one is active, your audio is sent to tha...</summary>
    public static string Onboarding_Cloud_Body => Localizer.Lookup(nameof(Onboarding_Cloud_Body));

    /// <summary>Cloud engines are opt-in</summary>
    public static string Onboarding_Cloud_Title => Localizer.Lookup(nameof(Onboarding_Cloud_Title));

    /// <summary>Parlotype ships several recognition engines — switch between them in the highlighted list. Parakeet v3 is the default...</summary>
    public static string Onboarding_Engine_Body => Localizer.Lookup(nameof(Onboarding_Engine_Body));

    /// <summary>Choose a speech engine</summary>
    public static string Onboarding_Engine_Title => Localizer.Lookup(nameof(Onboarding_Engine_Title));

    /// <summary>No dictation hotkey is set — use the record button on the widget, or add a hotkey in Settings → Hotkeys.</summary>
    public static string Onboarding_Hotkeys_None => Localizer.Lookup(nameof(Onboarding_Hotkeys_None));

    /// <summary>Each local engine offers models of different sizes — larger models are more accurate but slower and take more disk sp...</summary>
    public static string Onboarding_Model_Body => Localizer.Lookup(nameof(Onboarding_Model_Body));

    /// <summary>Pick a model</summary>
    public static string Onboarding_Model_Title => Localizer.Lookup(nameof(Onboarding_Model_Title));

    /// <summary>Back</summary>
    public static string Onboarding_Nav_Back => Localizer.Lookup(nameof(Onboarding_Nav_Back));

    /// <summary>Finish</summary>
    public static string Onboarding_Nav_Finish => Localizer.Lookup(nameof(Onboarding_Nav_Finish));

    /// <summary>Next</summary>
    public static string Onboarding_Nav_Next => Localizer.Lookup(nameof(Onboarding_Nav_Next));

    /// <summary>Skip tour</summary>
    public static string Onboarding_Nav_Skip => Localizer.Lookup(nameof(Onboarding_Nav_Skip));

    /// <summary>Step {0} of {1}</summary>
    public static string Onboarding_Progress_Format => Localizer.Lookup(nameof(Onboarding_Progress_Format));
    /// <summary>Step {0} of {1}</summary>
    public static string Format_Onboarding_Progress_Format(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Onboarding_Progress_Format, arg0, arg1);

    /// <summary>Dictate anywhere with your hotkeys or the widget button. Engines, models, hotkeys and languages live in Settings — an...</summary>
    public static string Onboarding_Recap_Body => Localizer.Lookup(nameof(Onboarding_Recap_Body));

    /// <summary>You're all set</summary>
    public static string Onboarding_Recap_Title => Localizer.Lookup(nameof(Onboarding_Recap_Title));

    /// <summary>Press one of your dictation hotkeys, or click the highlighted record button on the widget. When you finish speaking, ...</summary>
    public static string Onboarding_Recording_Body => Localizer.Lookup(nameof(Onboarding_Recording_Body));

    /// <summary>Esc — cancel the current recording without typing anything</summary>
    public static string Onboarding_Recording_EscLine => Localizer.Lookup(nameof(Onboarding_Recording_EscLine));

    /// <summary>Start dictating</summary>
    public static string Onboarding_Recording_Title => Localizer.Lookup(nameof(Onboarding_Recording_Title));

    /// <summary>Hiding or closing the widget does not quit Parlotype — it keeps listening for your hotkeys from the system tray. Clic...</summary>
    public static string Onboarding_Tray_Body => Localizer.Lookup(nameof(Onboarding_Tray_Body));

    /// <summary>Parlotype lives in the tray</summary>
    public static string Onboarding_Tray_Title => Localizer.Lookup(nameof(Onboarding_Tray_Title));

    /// <summary>Parlotype turns speech into text anywhere on your computer: dictate into any app, and the recognized text is typed ri...</summary>
    public static string Onboarding_Welcome_Body => Localizer.Lookup(nameof(Onboarding_Welcome_Body));

    /// <summary>Welcome to Parlotype</summary>
    public static string Onboarding_Welcome_Title => Localizer.Lookup(nameof(Onboarding_Welcome_Title));

    /// <summary>This small always-on-top window is your dictation control. The big button starts and stops recording; hover the card ...</summary>
    public static string Onboarding_Widget_Body => Localizer.Lookup(nameof(Onboarding_Widget_Body));

    /// <summary>The recording widget</summary>
    public static string Onboarding_Widget_Title => Localizer.Lookup(nameof(Onboarding_Widget_Title));

    /// <summary>Parlotype tour</summary>
    public static string Onboarding_WindowTitle => Localizer.Lookup(nameof(Onboarding_WindowTitle));

    /// <summary>Appearance</summary>
    public static string Settings_Category_Appearance => Localizer.Lookup(nameof(Settings_Category_Appearance));

    /// <summary>Application</summary>
    public static string Settings_Category_Application => Localizer.Lookup(nameof(Settings_Category_Application));

    /// <summary>Audio</summary>
    public static string Settings_Category_Audio => Localizer.Lookup(nameof(Settings_Category_Audio));

    /// <summary>Input</summary>
    public static string Settings_Category_Input => Localizer.Lookup(nameof(Settings_Category_Input));

    /// <summary>Speech engine</summary>
    public static string Settings_Category_SpeechEngine => Localizer.Lookup(nameof(Settings_Category_SpeechEngine));

    /// <summary>API key</summary>
    public static string Settings_CloudProviders_ApiKeyLabel => Localizer.Lookup(nameof(Settings_CloudProviders_ApiKeyLabel));

    /// <summary>Base URL</summary>
    public static string Settings_CloudProviders_BaseUrlLabel => Localizer.Lookup(nameof(Settings_CloudProviders_BaseUrlLabel));

    /// <summary>Change</summary>
    public static string Settings_CloudProviders_ChangeButton => Localizer.Lookup(nameof(Settings_CloudProviders_ChangeButton));

    /// <summary>Bring your own API key. When a cloud engine is active, your audio recordings are sent to the configured provider for ...</summary>
    public static string Settings_CloudProviders_Intro => Localizer.Lookup(nameof(Settings_CloudProviders_Intro));

    /// <summary>✓ Saved</summary>
    public static string Settings_CloudProviders_KeySavedBadge => Localizer.Lookup(nameof(Settings_CloudProviders_KeySavedBadge));

    /// <summary>No key</summary>
    public static string Settings_CloudProviders_KeyStatus_None => Localizer.Lookup(nameof(Settings_CloudProviders_KeyStatus_None));

    /// <summary>Key saved</summary>
    public static string Settings_CloudProviders_KeyStatus_Saved => Localizer.Lookup(nameof(Settings_CloudProviders_KeyStatus_Saved));

    /// <summary>Model</summary>
    public static string Settings_CloudProviders_ModelLabel => Localizer.Lookup(nameof(Settings_CloudProviders_ModelLabel));

    /// <summary>Works with OpenAI, Groq, or any other host that implements the OpenAI transcription API.</summary>
    public static string Settings_CloudProviders_OpenAi_Description => Localizer.Lookup(nameof(Settings_CloudProviders_OpenAi_Description));

    /// <summary>OpenAI-compatible</summary>
    public static string Settings_CloudProviders_OpenAi_Name => Localizer.Lookup(nameof(Settings_CloudProviders_OpenAi_Name));

    /// <summary>Remove</summary>
    public static string Settings_CloudProviders_RemoveButton => Localizer.Lookup(nameof(Settings_CloudProviders_RemoveButton));

    /// <summary>Save</summary>
    public static string Settings_CloudProviders_SaveButton => Localizer.Lookup(nameof(Settings_CloudProviders_SaveButton));

    /// <summary>Cloud providers</summary>
    public static string Settings_CloudProviders_Title => Localizer.Lookup(nameof(Settings_CloudProviders_Title));

    /// <summary>xAI's Grok Speech-to-Text API.</summary>
    public static string Settings_CloudProviders_Xai_Description => Localizer.Lookup(nameof(Settings_CloudProviders_Xai_Description));

    /// <summary>xAI Grok</summary>
    public static string Settings_CloudProviders_Xai_Name => Localizer.Lookup(nameof(Settings_CloudProviders_Xai_Name));

    /// <summary>Copy path</summary>
    public static string Settings_Data_CopyPathButton => Localizer.Lookup(nameof(Settings_Data_CopyPathButton));

    /// <summary>This removes {0} from {1}.  Your settings and API keys are kept. Models download again automatically the next time yo...</summary>
    public static string Settings_Data_DeleteDialog_BodyFormat => Localizer.Lookup(nameof(Settings_Data_DeleteDialog_BodyFormat));
    /// <summary>This removes {0} from {1}.  Your settings and API keys are kept. Models download again automatically the next time yo...</summary>
    public static string Format_Settings_Data_DeleteDialog_BodyFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Data_DeleteDialog_BodyFormat, arg0, arg1);

    /// <summary>Delete models</summary>
    public static string Settings_Data_DeleteDialog_Confirm => Localizer.Lookup(nameof(Settings_Data_DeleteDialog_Confirm));

    /// <summary>Delete downloaded models?</summary>
    public static string Settings_Data_DeleteDialog_Title => Localizer.Lookup(nameof(Settings_Data_DeleteDialog_Title));

    /// <summary>Could not delete every file — something is still using it. Restart Parlotype and try again.</summary>
    public static string Settings_Data_DeleteFailed => Localizer.Lookup(nameof(Settings_Data_DeleteFailed));

    /// <summary>Delete downloaded models…</summary>
    public static string Settings_Data_DeleteModelsButton => Localizer.Lookup(nameof(Settings_Data_DeleteModelsButton));

    /// <summary>Where Parlotype keeps your models, settings and API keys.</summary>
    public static string Settings_Data_Description => Localizer.Lookup(nameof(Settings_Data_Description));

    /// <summary>Downloaded models:</summary>
    public static string Settings_Data_DownloadedModelsLabel => Localizer.Lookup(nameof(Settings_Data_DownloadedModelsLabel));

    /// <summary>Location</summary>
    public static string Settings_Data_LocationLabel => Localizer.Lookup(nameof(Settings_Data_LocationLabel));

    /// <summary>Downloaded models deleted.</summary>
    public static string Settings_Data_ModelsDeleted => Localizer.Lookup(nameof(Settings_Data_ModelsDeleted));

    /// <summary>Nothing downloaded</summary>
    public static string Settings_Data_NothingDownloaded => Localizer.Lookup(nameof(Settings_Data_NothingDownloaded));

    /// <summary>Open folder</summary>
    public static string Settings_Data_OpenFolderButton => Localizer.Lookup(nameof(Settings_Data_OpenFolderButton));

    /// <summary>Could not open the folder.</summary>
    public static string Settings_Data_OpenFolderFailed => Localizer.Lookup(nameof(Settings_Data_OpenFolderFailed));

    /// <summary>Path copied to the clipboard.</summary>
    public static string Settings_Data_PathCopied => Localizer.Lookup(nameof(Settings_Data_PathCopied));

    /// <summary>Could not copy the path.</summary>
    public static string Settings_Data_PathCopyFailed => Localizer.Lookup(nameof(Settings_Data_PathCopyFailed));

    /// <summary>Could not save that preference — uninstalling will still delete your downloaded models, settings and API keys. Please...</summary>
    public static string Settings_Data_SaveFailed_Delete => Localizer.Lookup(nameof(Settings_Data_SaveFailed_Delete));

    /// <summary>Could not save that preference. Uninstalling will still keep your data.</summary>
    public static string Settings_Data_SaveFailed_Keep => Localizer.Lookup(nameof(Settings_Data_SaveFailed_Keep));

    /// <summary>Data</summary>
    public static string Settings_Data_Title => Localizer.Lookup(nameof(Settings_Data_Title));

    /// <summary>Off by default, so reinstalling Parlotype does not cost you a multi-gigabyte re-download. When on, uninstalling also ...</summary>
    public static string Settings_Data_UninstallNote => Localizer.Lookup(nameof(Settings_Data_UninstallNote));

    /// <summary>Keep my data when I uninstall Parlotype</summary>
    public static string Settings_Data_UninstallToggleOff => Localizer.Lookup(nameof(Settings_Data_UninstallToggleOff));

    /// <summary>Delete everything when I uninstall Parlotype</summary>
    public static string Settings_Data_UninstallToggleOn => Localizer.Lookup(nameof(Settings_Data_UninstallToggleOn));

    /// <summary>Choose which engine transcribes your speech. Changes take effect on next recording.</summary>
    public static string Settings_Engine_Description => Localizer.Lookup(nameof(Settings_Engine_Description));

    /// <summary>Google Gemma 4 E4B via llama.cpp. Requires ~10 GB download. English only. Best on clean speech.</summary>
    public static string Settings_Engine_Gemma4_Description => Localizer.Lookup(nameof(Settings_Engine_Gemma4_Description));

    /// <summary>Gemma 4 (Experimental)</summary>
    public static string Settings_Engine_Gemma4_Name => Localizer.Lookup(nameof(Settings_Engine_Gemma4_Name));

    /// <summary>Gemma 4 (Experimental)</summary>
    public static string Settings_Engine_Gemma4SectionLabel => Localizer.Lookup(nameof(Settings_Engine_Gemma4SectionLabel));

    /// <summary>Gemma 4 E4B runs via a local llama-server process (llama.cpp, Vulkan). English transcription only. Works best with cl...</summary>
    public static string Settings_Engine_Gemma4SectionNote => Localizer.Lookup(nameof(Settings_Engine_Gemma4SectionNote));

    /// <summary>Speech Engine</summary>
    public static string Settings_Engine_Heading => Localizer.Lookup(nameof(Settings_Engine_Heading));

    /// <summary>Cloud transcription via your own OpenAI, Groq, or compatible API key. Audio is sent to the configured provider — noth...</summary>
    public static string Settings_Engine_OpenAiCompatible_Description => Localizer.Lookup(nameof(Settings_Engine_OpenAiCompatible_Description));

    /// <summary>OpenAI-compatible (Cloud)</summary>
    public static string Settings_Engine_OpenAiCompatible_Name => Localizer.Lookup(nameof(Settings_Engine_OpenAiCompatible_Name));

    /// <summary>NVIDIA Parakeet via ONNX. ~670 MB download. 25 European languages, auto-detected. Fastest engine — runs on any CPU, n...</summary>
    public static string Settings_Engine_Parakeet_Description => Localizer.Lookup(nameof(Settings_Engine_Parakeet_Description));

    /// <summary>Parakeet v3 (Recommended)</summary>
    public static string Settings_Engine_Parakeet_Name => Localizer.Lookup(nameof(Settings_Engine_Parakeet_Name));

    /// <summary>When enabled, the speech model loads in the background at app startup so your first recording starts instantly. Uses ...</summary>
    public static string Settings_Engine_PreloadNote => Localizer.Lookup(nameof(Settings_Engine_PreloadNote));

    /// <summary>Load model on first use</summary>
    public static string Settings_Engine_PreloadToggleOff => Localizer.Lookup(nameof(Settings_Engine_PreloadToggleOff));

    /// <summary>Preload model on startup</summary>
    public static string Settings_Engine_PreloadToggleOn => Localizer.Lookup(nameof(Settings_Engine_PreloadToggleOn));

    /// <summary>Engine</summary>
    public static string Settings_Engine_Title => Localizer.Lookup(nameof(Settings_Engine_Title));

    /// <summary>Local speech recognition via Whisper.net. Well-tested, ~99 languages, source selection and translation to English.</summary>
    public static string Settings_Engine_Whisper_Description => Localizer.Lookup(nameof(Settings_Engine_Whisper_Description));

    /// <summary>Whisper</summary>
    public static string Settings_Engine_Whisper_Name => Localizer.Lookup(nameof(Settings_Engine_Whisper_Name));

    /// <summary>xAI Grok Speech-to-Text via your own xAI API key. Audio is sent to xAI — nothing runs locally. Fast even on weak hard...</summary>
    public static string Settings_Engine_XaiGrok_Description => Localizer.Lookup(nameof(Settings_Engine_XaiGrok_Description));

    /// <summary>xAI Grok (Cloud)</summary>
    public static string Settings_Engine_XaiGrok_Name => Localizer.Lookup(nameof(Settings_Engine_XaiGrok_Name));

    /// <summary>Choose a Gemma 4 variant for the llama.cpp engine. E4B is more accurate; E2B is faster (fewer active parameters). Eac...</summary>
    public static string Settings_Gemma4Model_Description => Localizer.Lookup(nameof(Settings_Gemma4Model_Description));

    /// <summary>Gemma 4 model</summary>
    public static string Settings_Gemma4Model_Title => Localizer.Lookup(nameof(Settings_Gemma4Model_Title));

    /// <summary>Add hotkey</summary>
    public static string Settings_Hotkeys_AddButton => Localizer.Lookup(nameof(Settings_Hotkeys_AddButton));

    /// <summary>{0} is already bound to {1}.</summary>
    public static string Settings_Hotkeys_Conflict_AlreadyBoundFormat => Localizer.Lookup(nameof(Settings_Hotkeys_Conflict_AlreadyBoundFormat));
    /// <summary>{0} is already bound to {1}.</summary>
    public static string Format_Settings_Hotkeys_Conflict_AlreadyBoundFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Hotkeys_Conflict_AlreadyBoundFormat, arg0, arg1);

    /// <summary>On European keyboard layouts AltGr acts as Ctrl+Alt, so {0} can fire while typing accented characters. Ctrl+Alt+Space...</summary>
    public static string Settings_Hotkeys_Conflict_AltGrFormat => Localizer.Lookup(nameof(Settings_Hotkeys_Conflict_AltGrFormat));
    /// <summary>On European keyboard layouts AltGr acts as Ctrl+Alt, so {0} can fire while typing accented characters. Ctrl+Alt+Space...</summary>
    public static string Format_Settings_Hotkeys_Conflict_AltGrFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Hotkeys_Conflict_AltGrFormat, arg0);

    /// <summary>That combination can't be used as a dictation hotkey.</summary>
    public static string Settings_Hotkeys_Conflict_Invalid => Localizer.Lookup(nameof(Settings_Hotkeys_Conflict_Invalid));

    /// <summary>push to talk</summary>
    public static string Settings_Hotkeys_Conflict_Mode_PushToTalk => Localizer.Lookup(nameof(Settings_Hotkeys_Conflict_Mode_PushToTalk));

    /// <summary>toggle</summary>
    public static string Settings_Hotkeys_Conflict_Mode_Toggle => Localizer.Lookup(nameof(Settings_Hotkeys_Conflict_Mode_Toggle));

    /// <summary>{0} shows parameter hints in Visual Studio and VS Code.</summary>
    public static string Settings_Hotkeys_Conflict_ParameterHintsFormat => Localizer.Lookup(nameof(Settings_Hotkeys_Conflict_ParameterHintsFormat));
    /// <summary>{0} shows parameter hints in Visual Studio and VS Code.</summary>
    public static string Format_Settings_Hotkeys_Conflict_ParameterHintsFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Hotkeys_Conflict_ParameterHintsFormat, arg0);

    /// <summary>{0} is reserved: {1}</summary>
    public static string Settings_Hotkeys_Conflict_ReservedFormat => Localizer.Lookup(nameof(Settings_Hotkeys_Conflict_ReservedFormat));
    /// <summary>{0} is reserved: {1}</summary>
    public static string Format_Settings_Hotkeys_Conflict_ReservedFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Hotkeys_Conflict_ReservedFormat, arg0, arg1);

    /// <summary>Hold a key to talk, or double-tap to dictate hands-free. Press Esc while recording to discard it.</summary>
    public static string Settings_Hotkeys_Description => Localizer.Lookup(nameof(Settings_Hotkeys_Description));

    /// <summary>Double-tap {0}</summary>
    public static string Settings_Hotkeys_Gesture_DoubleTapFormat => Localizer.Lookup(nameof(Settings_Hotkeys_Gesture_DoubleTapFormat));
    /// <summary>Double-tap {0}</summary>
    public static string Format_Settings_Hotkeys_Gesture_DoubleTapFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Hotkeys_Gesture_DoubleTapFormat, arg0);

    /// <summary>Hold {0}</summary>
    public static string Settings_Hotkeys_Gesture_HoldFormat => Localizer.Lookup(nameof(Settings_Hotkeys_Gesture_HoldFormat));
    /// <summary>Hold {0}</summary>
    public static string Format_Settings_Hotkeys_Gesture_HoldFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Hotkeys_Gesture_HoldFormat, arg0);

    /// <summary>{0} — {1}</summary>
    public static string Settings_Hotkeys_LineFormat => Localizer.Lookup(nameof(Settings_Hotkeys_LineFormat));
    /// <summary>{0} — {1}</summary>
    public static string Format_Settings_Hotkeys_LineFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Hotkeys_LineFormat, arg0, arg1);

    /// <summary>Push to talk</summary>
    public static string Settings_Hotkeys_Mode_PushToTalk => Localizer.Lookup(nameof(Settings_Hotkeys_Mode_PushToTalk));

    /// <summary>Toggle</summary>
    public static string Settings_Hotkeys_Mode_Toggle => Localizer.Lookup(nameof(Settings_Hotkeys_Mode_Toggle));

    /// <summary>Switch between push-to-talk and toggle</summary>
    public static string Settings_Hotkeys_ModeToggleTooltip => Localizer.Lookup(nameof(Settings_Hotkeys_ModeToggleTooltip));

    /// <summary>Left {0}</summary>
    public static string Settings_Hotkeys_Modifier_LeftFormat => Localizer.Lookup(nameof(Settings_Hotkeys_Modifier_LeftFormat));
    /// <summary>Left {0}</summary>
    public static string Format_Settings_Hotkeys_Modifier_LeftFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Hotkeys_Modifier_LeftFormat, arg0);

    /// <summary>Right {0}</summary>
    public static string Settings_Hotkeys_Modifier_RightFormat => Localizer.Lookup(nameof(Settings_Hotkeys_Modifier_RightFormat));
    /// <summary>Right {0}</summary>
    public static string Format_Settings_Hotkeys_Modifier_RightFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Hotkeys_Modifier_RightFormat, arg0);

    /// <summary>No hotkeys configured — dictation can only be started from the widget.</summary>
    public static string Settings_Hotkeys_None => Localizer.Lookup(nameof(Settings_Hotkeys_None));

    /// <summary>Record a chord…</summary>
    public static string Settings_Hotkeys_Recorder_Idle => Localizer.Lookup(nameof(Settings_Hotkeys_Recorder_Idle));

    /// <summary>Press a key combination…</summary>
    public static string Settings_Hotkeys_Recorder_Listening => Localizer.Lookup(nameof(Settings_Hotkeys_Recorder_Listening));

    /// <summary>Remove this hotkey</summary>
    public static string Settings_Hotkeys_RemoveTooltip => Localizer.Lookup(nameof(Settings_Hotkeys_RemoveTooltip));

    /// <summary>Open File Explorer</summary>
    public static string Settings_Hotkeys_Reserved_FileExplorer => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_FileExplorer));

    /// <summary>Open Game Bar</summary>
    public static string Settings_Hotkeys_Reserved_GameBar => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_GameBar));

    /// <summary>Lock workstation</summary>
    public static string Settings_Hotkeys_Reserved_LockWorkstation => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_LockWorkstation));

    /// <summary>Close window (macOS)</summary>
    public static string Settings_Hotkeys_Reserved_MacCloseWindow => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_MacCloseWindow));

    /// <summary>Quit application (macOS)</summary>
    public static string Settings_Hotkeys_Reserved_MacQuit => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_MacQuit));

    /// <summary>Project display</summary>
    public static string Settings_Hotkeys_Reserved_ProjectDisplay => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_ProjectDisplay));

    /// <summary>Quick Link menu</summary>
    public static string Settings_Hotkeys_Reserved_QuickLinkMenu => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_QuickLinkMenu));

    /// <summary>Open Run dialog</summary>
    public static string Settings_Hotkeys_Reserved_RunDialog => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_RunDialog));

    /// <summary>Screenshot</summary>
    public static string Settings_Hotkeys_Reserved_Screenshot => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_Screenshot));

    /// <summary>Security screen</summary>
    public static string Settings_Hotkeys_Reserved_SecurityScreen => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_SecurityScreen));

    /// <summary>Show/hide desktop</summary>
    public static string Settings_Hotkeys_Reserved_ShowDesktop => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_ShowDesktop));

    /// <summary>Spotlight search (macOS) / input source switching</summary>
    public static string Settings_Hotkeys_Reserved_Spotlight => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_Spotlight));

    /// <summary>Switch input source</summary>
    public static string Settings_Hotkeys_Reserved_SwitchInputSource => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_SwitchInputSource));

    /// <summary>Task View</summary>
    public static string Settings_Hotkeys_Reserved_TaskView => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_TaskView));

    /// <summary>Windows Voice Typing; hide window on macOS and GNOME</summary>
    public static string Settings_Hotkeys_Reserved_VoiceTyping => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_VoiceTyping));

    /// <summary>Open Settings</summary>
    public static string Settings_Hotkeys_Reserved_WindowsSettings => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_WindowsSettings));

    /// <summary>Windows Speech Recognition</summary>
    public static string Settings_Hotkeys_Reserved_WindowsSpeechRecognition => Localizer.Lookup(nameof(Settings_Hotkeys_Reserved_WindowsSpeechRecognition));

    /// <summary>Hotkeys</summary>
    public static string Settings_Hotkeys_Title => Localizer.Lookup(nameof(Settings_Hotkeys_Title));

    /// <summary>The language Parlotype's own windows are written in. It has no effect on which languages you can dictate in — those a...</summary>
    public static string Settings_InterfaceLanguage_Description => Localizer.Lookup(nameof(Settings_InterfaceLanguage_Description));

    /// <summary>System default</summary>
    public static string Settings_InterfaceLanguage_System => Localizer.Lookup(nameof(Settings_InterfaceLanguage_System));

    /// <summary>Follows Windows — currently {0}</summary>
    public static string Settings_InterfaceLanguage_SystemDetailFormat => Localizer.Lookup(nameof(Settings_InterfaceLanguage_SystemDetailFormat));
    /// <summary>Follows Windows — currently {0}</summary>
    public static string Format_Settings_InterfaceLanguage_SystemDetailFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_InterfaceLanguage_SystemDetailFormat, arg0);

    /// <summary>Follows Windows — not translated yet, so English is used</summary>
    public static string Settings_InterfaceLanguage_SystemDetailUnsupported => Localizer.Lookup(nameof(Settings_InterfaceLanguage_SystemDetailUnsupported));

    /// <summary>Interface language</summary>
    public static string Settings_InterfaceLanguage_Title => Localizer.Lookup(nameof(Settings_InterfaceLanguage_Title));

    /// <summary>One relationship, read left to right: you speak the source, Parlotype types the target. The connector between them tu...</summary>
    public static string Settings_Language_Description => Localizer.Lookup(nameof(Settings_Language_Description));

    /// <summary>Paused — this model can't translate</summary>
    public static string Settings_Language_PausedSubLine => Localizer.Lookup(nameof(Settings_Language_PausedSubLine));

    /// <summary>You speak</summary>
    public static string Settings_Language_SourceCaption => Localizer.Lookup(nameof(Settings_Language_SourceCaption));

    /// <summary>Parlotype types</summary>
    public static string Settings_Language_TargetCaption => Localizer.Lookup(nameof(Settings_Language_TargetCaption));

    /// <summary>Language</summary>
    public static string Settings_Language_Title => Localizer.Lookup(nameof(Settings_Language_Title));

    /// <summary>Not supported by this model</summary>
    public static string Settings_Language_UnavailableSubtitle => Localizer.Lookup(nameof(Settings_Language_UnavailableSubtitle));

    /// <summary>Translation unavailable</summary>
    public static string Settings_Language_UnavailableTitle => Localizer.Lookup(nameof(Settings_Language_UnavailableTitle));

    /// <summary>Audio:</summary>
    public static string Settings_LlamaCpp_AudioLabel => Localizer.Lookup(nameof(Settings_LlamaCpp_AudioLabel));

    /// <summary>Not supported</summary>
    public static string Settings_LlamaCpp_AudioNotSupported => Localizer.Lookup(nameof(Settings_LlamaCpp_AudioNotSupported));

    /// <summary>Supported</summary>
    public static string Settings_LlamaCpp_AudioSupported => Localizer.Lookup(nameof(Settings_LlamaCpp_AudioSupported));

    /// <summary>Available builds</summary>
    public static string Settings_LlamaCpp_AvailableBuildsHeading => Localizer.Lookup(nameof(Settings_LlamaCpp_AvailableBuildsHeading));

    /// <summary>Unknown</summary>
    public static string Settings_LlamaCpp_Backend_Unknown => Localizer.Lookup(nameof(Settings_LlamaCpp_Backend_Unknown));

    /// <summary>Browse…</summary>
    public static string Settings_LlamaCpp_BrowseButton => Localizer.Lookup(nameof(Settings_LlamaCpp_BrowseButton));

    /// <summary>Build:</summary>
    public static string Settings_LlamaCpp_BuildLabel => Localizer.Lookup(nameof(Settings_LlamaCpp_BuildLabel));

    /// <summary>Check for updates</summary>
    public static string Settings_LlamaCpp_CheckUpdatesButton => Localizer.Lookup(nameof(Settings_LlamaCpp_CheckUpdatesButton));

    /// <summary>+ CUDA runtime</summary>
    public static string Settings_LlamaCpp_CudaRuntimeBadge => Localizer.Lookup(nameof(Settings_LlamaCpp_CudaRuntimeBadge));

    /// <summary>Browse, install, and manage llama-server builds. The active install powers Gemma 4 transcription.</summary>
    public static string Settings_LlamaCpp_Description => Localizer.Lookup(nameof(Settings_LlamaCpp_Description));

    /// <summary>Select llama-server folder</summary>
    public static string Settings_LlamaCpp_FolderPickerTitle => Localizer.Lookup(nameof(Settings_LlamaCpp_FolderPickerTitle));

    /// <summary>llama.cpp</summary>
    public static string Settings_LlamaCpp_Heading => Localizer.Lookup(nameof(Settings_LlamaCpp_Heading));

    /// <summary>Install</summary>
    public static string Settings_LlamaCpp_InstallButton => Localizer.Lookup(nameof(Settings_LlamaCpp_InstallButton));

    /// <summary>Installed</summary>
    public static string Settings_LlamaCpp_InstalledBadge => Localizer.Lookup(nameof(Settings_LlamaCpp_InstalledBadge));

    /// <summary>Installed</summary>
    public static string Settings_LlamaCpp_InstalledHeading => Localizer.Lookup(nameof(Settings_LlamaCpp_InstalledHeading));

    /// <summary>(loading…)</summary>
    public static string Settings_LlamaCpp_Loading => Localizer.Lookup(nameof(Settings_LlamaCpp_Loading));

    /// <summary>Managed</summary>
    public static string Settings_LlamaCpp_ManagedBadge => Localizer.Lookup(nameof(Settings_LlamaCpp_ManagedBadge));

    /// <summary>Manual</summary>
    public static string Settings_LlamaCpp_ManualBadge => Localizer.Lookup(nameof(Settings_LlamaCpp_ManualBadge));

    /// <summary>No folder chosen — select the folder containing llama-server.exe</summary>
    public static string Settings_LlamaCpp_ManualFolderPlaceholder => Localizer.Lookup(nameof(Settings_LlamaCpp_ManualFolderPlaceholder));

    /// <summary>Choose the folder containing llama-server.exe and click Save before switching to the manual install.</summary>
    public static string Settings_LlamaCpp_ManualFolderRequiredError => Localizer.Lookup(nameof(Settings_LlamaCpp_ManualFolderRequiredError));

    /// <summary>Point at a folder containing llama-server.exe that you downloaded yourself.</summary>
    public static string Settings_LlamaCpp_ManualHint => Localizer.Lookup(nameof(Settings_LlamaCpp_ManualHint));

    /// <summary>Manual install</summary>
    public static string Settings_LlamaCpp_ManualInstallHeading => Localizer.Lookup(nameof(Settings_LlamaCpp_ManualInstallHeading));

    /// <summary>⚠ missing</summary>
    public static string Settings_LlamaCpp_MissingBadge => Localizer.Lookup(nameof(Settings_LlamaCpp_MissingBadge));

    /// <summary>Model:</summary>
    public static string Settings_LlamaCpp_ModelLabel => Localizer.Lookup(nameof(Settings_LlamaCpp_ModelLabel));

    /// <summary>No builds matched the current OS / architecture.</summary>
    public static string Settings_LlamaCpp_NoBuildsMatched => Localizer.Lookup(nameof(Settings_LlamaCpp_NoBuildsMatched));

    /// <summary>No managed installs yet. Pick one from the Available list below.</summary>
    public static string Settings_LlamaCpp_NoManagedInstalls => Localizer.Lookup(nameof(Settings_LlamaCpp_NoManagedInstalls));

    /// <summary>Not managed by Parlotype</summary>
    public static string Settings_LlamaCpp_NotManagedBadge => Localizer.Lookup(nameof(Settings_LlamaCpp_NotManagedBadge));

    /// <summary>Uninstalling Parlotype — or re-running its installer — deletes its install folder and everything under it, including ...</summary>
    public static string Settings_LlamaCpp_PackFolderWarningBody => Localizer.Lookup(nameof(Settings_LlamaCpp_PackFolderWarningBody));

    /// <summary>⚠ This folder is erased when Parlotype is uninstalled</summary>
    public static string Settings_LlamaCpp_PackFolderWarningHeading => Localizer.Lookup(nameof(Settings_LlamaCpp_PackFolderWarningHeading));

    /// <summary>Install folder:</summary>
    public static string Settings_LlamaCpp_PackFolderWarningPathLabel => Localizer.Lookup(nameof(Settings_LlamaCpp_PackFolderWarningPathLabel));

    /// <summary>Path:</summary>
    public static string Settings_LlamaCpp_PathLabel => Localizer.Lookup(nameof(Settings_LlamaCpp_PathLabel));

    /// <summary>⚠ Port Conflict</summary>
    public static string Settings_LlamaCpp_PortConflictHeading => Localizer.Lookup(nameof(Settings_LlamaCpp_PortConflictHeading));

    /// <summary>Change the port below and click Save.</summary>
    public static string Settings_LlamaCpp_PortConflictHint => Localizer.Lookup(nameof(Settings_LlamaCpp_PortConflictHint));

    /// <summary>Port must be a number between 1 and 65535.</summary>
    public static string Settings_LlamaCpp_PortRangeError => Localizer.Lookup(nameof(Settings_LlamaCpp_PortRangeError));

    /// <summary>Refresh</summary>
    public static string Settings_LlamaCpp_RefreshButton => Localizer.Lookup(nameof(Settings_LlamaCpp_RefreshButton));

    /// <summary>Refresh list</summary>
    public static string Settings_LlamaCpp_RefreshListButton => Localizer.Lookup(nameof(Settings_LlamaCpp_RefreshListButton));

    /// <summary>Reset</summary>
    public static string Settings_LlamaCpp_ResetButton => Localizer.Lookup(nameof(Settings_LlamaCpp_ResetButton));

    /// <summary>Running install:</summary>
    public static string Settings_LlamaCpp_RunningInstallLabel => Localizer.Lookup(nameof(Settings_LlamaCpp_RunningInstallLabel));

    /// <summary>Save</summary>
    public static string Settings_LlamaCpp_SaveButton => Localizer.Lookup(nameof(Settings_LlamaCpp_SaveButton));

    /// <summary>Selection will take effect on the next recording.</summary>
    public static string Settings_LlamaCpp_SelectionNote => Localizer.Lookup(nameof(Settings_LlamaCpp_SelectionNote));

    /// <summary>Port for llama-server (default: 8321). Changes take effect on next recording.</summary>
    public static string Settings_LlamaCpp_ServerPortDescription => Localizer.Lookup(nameof(Settings_LlamaCpp_ServerPortDescription));

    /// <summary>Server Port</summary>
    public static string Settings_LlamaCpp_ServerPortHeading => Localizer.Lookup(nameof(Settings_LlamaCpp_ServerPortHeading));

    /// <summary>Connected</summary>
    public static string Settings_LlamaCpp_Status_Connected => Localizer.Lookup(nameof(Settings_LlamaCpp_Status_Connected));

    /// <summary>Disconnected</summary>
    public static string Settings_LlamaCpp_Status_Disconnected => Localizer.Lookup(nameof(Settings_LlamaCpp_Status_Disconnected));

    /// <summary>Error</summary>
    public static string Settings_LlamaCpp_Status_Error => Localizer.Lookup(nameof(Settings_LlamaCpp_Status_Error));

    /// <summary>Invalid port</summary>
    public static string Settings_LlamaCpp_Status_InvalidPort => Localizer.Lookup(nameof(Settings_LlamaCpp_Status_InvalidPort));

    /// <summary>Loading model...</summary>
    public static string Settings_LlamaCpp_Status_LoadingModel => Localizer.Lookup(nameof(Settings_LlamaCpp_Status_LoadingModel));

    /// <summary>Not probed</summary>
    public static string Settings_LlamaCpp_Status_NotProbed => Localizer.Lookup(nameof(Settings_LlamaCpp_Status_NotProbed));

    /// <summary>Port conflict</summary>
    public static string Settings_LlamaCpp_Status_PortConflict => Localizer.Lookup(nameof(Settings_LlamaCpp_Status_PortConflict));

    /// <summary>Uninstall</summary>
    public static string Settings_LlamaCpp_UninstallButton => Localizer.Lookup(nameof(Settings_LlamaCpp_UninstallButton));

    /// <summary>A newer build is available on GitHub: </summary>
    public static string Settings_LlamaCpp_UpdateAvailableBody => Localizer.Lookup(nameof(Settings_LlamaCpp_UpdateAvailableBody));

    /// <summary>Update available</summary>
    public static string Settings_LlamaCpp_UpdateAvailableHeading => Localizer.Lookup(nameof(Settings_LlamaCpp_UpdateAvailableHeading));

    /// <summary>Use this</summary>
    public static string Settings_LlamaCpp_UseThisRadio => Localizer.Lookup(nameof(Settings_LlamaCpp_UseThisRadio));

    /// <summary>Use this install</summary>
    public static string Settings_LlamaCpp_UseThisTooltip => Localizer.Lookup(nameof(Settings_LlamaCpp_UseThisTooltip));

    /// <summary>llama.cpp server</summary>
    public static string Settings_LlamaCppServer_Title => Localizer.Lookup(nameof(Settings_LlamaCppServer_Title));

    /// <summary>Choose the input device used for transcription.</summary>
    public static string Settings_Microphone_Description => Localizer.Lookup(nameof(Settings_Microphone_Description));

    /// <summary>System default</summary>
    public static string Settings_Microphone_SystemDefault => Localizer.Lookup(nameof(Settings_Microphone_SystemDefault));

    /// <summary>Microphone</summary>
    public static string Settings_Microphone_Title => Localizer.Lookup(nameof(Settings_Microphone_Title));

    /// <summary>Delete</summary>
    public static string Settings_Model_DeleteButton => Localizer.Lookup(nameof(Settings_Model_DeleteButton));

    /// <summary>Download</summary>
    public static string Settings_Model_DownloadButton => Localizer.Lookup(nameof(Settings_Model_DownloadButton));

    /// <summary>Installed</summary>
    public static string Settings_Model_Installed => Localizer.Lookup(nameof(Settings_Model_Installed));

    /// <summary>Settings</summary>
    public static string Settings_NavHeading => Localizer.Lookup(nameof(Settings_NavHeading));

    /// <summary>NVIDIA Parakeet runs fully on the CPU — no GPU needed. It transcribes 25 European languages (detected automatically) ...</summary>
    public static string Settings_ParakeetModel_Description => Localizer.Lookup(nameof(Settings_ParakeetModel_Description));

    /// <summary>Parakeet model</summary>
    public static string Settings_ParakeetModel_Title => Localizer.Lookup(nameof(Settings_ParakeetModel_Title));

    /// <summary>Built-in</summary>
    public static string Settings_Prompts_BuiltInBadge => Localizer.Lookup(nameof(Settings_Prompts_BuiltInBadge));

    /// <summary>{0} (copy)</summary>
    public static string Settings_Prompts_CopySuffixFormat => Localizer.Lookup(nameof(Settings_Prompts_CopySuffixFormat));
    /// <summary>{0} (copy)</summary>
    public static string Format_Settings_Prompts_CopySuffixFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Prompts_CopySuffixFormat, arg0);

    /// <summary>Delete</summary>
    public static string Settings_Prompts_DeleteButton => Localizer.Lookup(nameof(Settings_Prompts_DeleteButton));

    /// <summary>The instruction sent to the Gemma 4 engine with every transcription. The active prompt is marked with the accent bar.</summary>
    public static string Settings_Prompts_Description => Localizer.Lookup(nameof(Settings_Prompts_Description));

    /// <summary>Duplicate</summary>
    public static string Settings_Prompts_DuplicateButton => Localizer.Lookup(nameof(Settings_Prompts_DuplicateButton));

    /// <summary>Edit</summary>
    public static string Settings_Prompts_EditButton => Localizer.Lookup(nameof(Settings_Prompts_EditButton));

    /// <summary>Placeholders:</summary>
    public static string Settings_Prompts_Editor_PlaceholdersLabel => Localizer.Lookup(nameof(Settings_Prompts_Editor_PlaceholdersLabel));

    /// <summary>— the spoken language ("the detected language" when auto-detecting);</summary>
    public static string Settings_Prompts_Editor_SpeechLangHint => Localizer.Lookup(nameof(Settings_Prompts_Editor_SpeechLangHint));

    /// <summary>— the output language, which equals the spoken one unless translation is active.</summary>
    public static string Settings_Prompts_Editor_TextLangHint => Localizer.Lookup(nameof(Settings_Prompts_Editor_TextLangHint));

    /// <summary>When translation is active, a "then translate into ..." instruction is appended to your prompt automatically.</summary>
    public static string Settings_Prompts_Editor_TranslationNote => Localizer.Lookup(nameof(Settings_Prompts_Editor_TranslationNote));

    /// <summary>The built-in default carries three bodies and the engine picks one per transcription: a transcription body, where the...</summary>
    public static string Settings_Prompts_Help_BuiltInBody => Localizer.Lookup(nameof(Settings_Prompts_Help_BuiltInBody));

    /// <summary>Built-in vs. custom prompts</summary>
    public static string Settings_Prompts_Help_BuiltInHeading => Localizer.Lookup(nameof(Settings_Prompts_Help_BuiltInHeading));

    /// <summary>A custom prompt has a single body. When translation applies, a "then translate into ..." instruction is appended to i...</summary>
    public static string Settings_Prompts_Help_CustomBody => Localizer.Lookup(nameof(Settings_Prompts_Help_CustomBody));

    /// <summary>Placeholders</summary>
    public static string Settings_Prompts_Help_PlaceholdersHeading => Localizer.Lookup(nameof(Settings_Prompts_Help_PlaceholdersHeading));

    /// <summary>— the spoken language, taken from the Languages settings page. With "Auto-detect" it renders as "the detected language".</summary>
    public static string Settings_Prompts_Help_SpeechLangDescription => Localizer.Lookup(nameof(Settings_Prompts_Help_SpeechLangDescription));

    /// <summary>— the output language. It differs from the spoken language only while translation is active; otherwise it renders as ...</summary>
    public static string Settings_Prompts_Help_TextLangDescription => Localizer.Lookup(nameof(Settings_Prompts_Help_TextLangDescription));

    /// <summary>Only when all three hold: the Translate toggle is on, an output language is selected, and it differs from the spoken ...</summary>
    public static string Settings_Prompts_Help_TranslationBody => Localizer.Lookup(nameof(Settings_Prompts_Help_TranslationBody));

    /// <summary>When translation is applied</summary>
    public static string Settings_Prompts_Help_TranslationHeading => Localizer.Lookup(nameof(Settings_Prompts_Help_TranslationHeading));

    /// <summary>How prompts work</summary>
    public static string Settings_Prompts_HelpHeader => Localizer.Lookup(nameof(Settings_Prompts_HelpHeader));

    /// <summary>Name</summary>
    public static string Settings_Prompts_NameLabel => Localizer.Lookup(nameof(Settings_Prompts_NameLabel));

    /// <summary>My prompt</summary>
    public static string Settings_Prompts_NamePlaceholder => Localizer.Lookup(nameof(Settings_Prompts_NamePlaceholder));

    /// <summary>New prompt</summary>
    public static string Settings_Prompts_NewButton => Localizer.Lookup(nameof(Settings_Prompts_NewButton));

    /// <summary>Save</summary>
    public static string Settings_Prompts_SaveButton => Localizer.Lookup(nameof(Settings_Prompts_SaveButton));

    /// <summary>Prompt text</summary>
    public static string Settings_Prompts_TextLabel => Localizer.Lookup(nameof(Settings_Prompts_TextLabel));

    /// <summary>Prompts</summary>
    public static string Settings_Prompts_Title => Localizer.Lookup(nameof(Settings_Prompts_Title));

    /// <summary>Try Vulkan, then fall back to CPU. Recommended.</summary>
    public static string Settings_Runtime_Auto_Description => Localizer.Lookup(nameof(Settings_Runtime_Auto_Description));

    /// <summary>Auto</summary>
    public static string Settings_Runtime_Auto_Name => Localizer.Lookup(nameof(Settings_Runtime_Auto_Name));

    /// <summary>Force CPU-only inference. Always works but slower for larger models.</summary>
    public static string Settings_Runtime_Cpu_Description => Localizer.Lookup(nameof(Settings_Runtime_Cpu_Description));

    /// <summary>CPU</summary>
    public static string Settings_Runtime_Cpu_Name => Localizer.Lookup(nameof(Settings_Runtime_Cpu_Name));

    /// <summary>Choose which Whisper.net backend runs the speech model. Changes take effect after restart.</summary>
    public static string Settings_Runtime_Description => Localizer.Lookup(nameof(Settings_Runtime_Description));

    /// <summary>Download Vulkan SDK →</summary>
    public static string Settings_Runtime_DownloadVulkanSdkButton => Localizer.Lookup(nameof(Settings_Runtime_DownloadVulkanSdkButton));

    /// <summary>Restart required</summary>
    public static string Settings_Runtime_RestartHeading => Localizer.Lookup(nameof(Settings_Runtime_RestartHeading));

    /// <summary>This session is already running the {0} runtime. Whisper picks its runtime once per launch, so restart Parlotype to s...</summary>
    public static string Settings_Runtime_RestartNoteFormat => Localizer.Lookup(nameof(Settings_Runtime_RestartNoteFormat));
    /// <summary>This session is already running the {0} runtime. Whisper picks its runtime once per launch, so restart Parlotype to s...</summary>
    public static string Format_Settings_Runtime_RestartNoteFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Runtime_RestartNoteFormat, arg0, arg1);

    /// <summary>Any GPU via Vulkan (AMD, Intel, NVIDIA). Requires GPU drivers with Vulkan support.</summary>
    public static string Settings_Runtime_Vulkan_Description => Localizer.Lookup(nameof(Settings_Runtime_Vulkan_Description));

    /// <summary>Vulkan</summary>
    public static string Settings_Runtime_Vulkan_Name => Localizer.Lookup(nameof(Settings_Runtime_Vulkan_Name));

    /// <summary>Vulkan loader (vulkan-1.dll) was not detected on this system.</summary>
    public static string Settings_Runtime_VulkanMissing => Localizer.Lookup(nameof(Settings_Runtime_VulkanMissing));

    /// <summary>Vulkan loader (vulkan-1.dll) not detected. Install GPU drivers or the Vulkan SDK.</summary>
    public static string Settings_Runtime_VulkanUnavailableReason => Localizer.Lookup(nameof(Settings_Runtime_VulkanUnavailableReason));

    /// <summary>How long to wait after speech ends before transcribing.</summary>
    public static string Settings_SilenceTimeout_Description => Localizer.Lookup(nameof(Settings_SilenceTimeout_Description));

    /// <summary>Applies when you toggle dictation on and off. Hold-to-talk ignores this — holding the key already says when you are d...</summary>
    public static string Settings_SilenceTimeout_HoldNote => Localizer.Lookup(nameof(Settings_SilenceTimeout_HoldNote));

    /// <summary>Silence timeout</summary>
    public static string Settings_SilenceTimeout_Title => Localizer.Lookup(nameof(Settings_SilenceTimeout_Title));

    /// <summary>Extended</summary>
    public static string Settings_SilenceTimeout_Wait_Extended => Localizer.Lookup(nameof(Settings_SilenceTimeout_Wait_Extended));

    /// <summary>Long</summary>
    public static string Settings_SilenceTimeout_Wait_Long => Localizer.Lookup(nameof(Settings_SilenceTimeout_Wait_Long));

    /// <summary>Medium</summary>
    public static string Settings_SilenceTimeout_Wait_Medium => Localizer.Lookup(nameof(Settings_SilenceTimeout_Wait_Medium));

    /// <summary>Very Long</summary>
    public static string Settings_SilenceTimeout_Wait_VeryLong => Localizer.Lookup(nameof(Settings_SilenceTimeout_Wait_VeryLong));

    /// <summary>{0} ({1}s)</summary>
    public static string Settings_SilenceTimeout_WaitFormat => Localizer.Lookup(nameof(Settings_SilenceTimeout_WaitFormat));
    /// <summary>{0} ({1}s)</summary>
    public static string Format_Settings_SilenceTimeout_WaitFormat(object? arg0, object? arg1) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_SilenceTimeout_WaitFormat, arg0, arg1);

    /// <summary>Open Task Manager, go to the Startup apps tab, select Parlotype and choose Enable. Windows keeps that decision separa...</summary>
    public static string Settings_Startup_BlockedBody => Localizer.Lookup(nameof(Settings_Startup_BlockedBody));

    /// <summary>Switched off in Windows</summary>
    public static string Settings_Startup_BlockedHeading => Localizer.Lookup(nameof(Settings_Startup_BlockedHeading));

    /// <summary>Parlotype listens for your dictation hotkey from the system tray, so it has to be running before you can dictate.</summary>
    public static string Settings_Startup_Description => Localizer.Lookup(nameof(Settings_Startup_Description));

    /// <summary>Windows has Parlotype switched off in Task Manager → Startup apps. Re-enable it there to let this setting take effect.</summary>
    public static string Settings_Startup_State_BlockedByWindows => Localizer.Lookup(nameof(Settings_Startup_State_BlockedByWindows));

    /// <summary>Parlotype only runs when you start it yourself.</summary>
    public static string Settings_Startup_State_Disabled => Localizer.Lookup(nameof(Settings_Startup_State_Disabled));

    /// <summary>Parlotype starts with Windows and waits in the tray — no window opens.</summary>
    public static string Settings_Startup_State_Enabled => Localizer.Lookup(nameof(Settings_Startup_State_Enabled));

    /// <summary>This build cannot start itself at sign-in — it was not installed from Setup.exe.</summary>
    public static string Settings_Startup_State_NotInstalled => Localizer.Lookup(nameof(Settings_Startup_State_NotInstalled));

    /// <summary>Startup</summary>
    public static string Settings_Startup_Title => Localizer.Lookup(nameof(Settings_Startup_Title));

    /// <summary>Do not start Parlotype automatically</summary>
    public static string Settings_Startup_ToggleOff => Localizer.Lookup(nameof(Settings_Startup_ToggleOff));

    /// <summary>Start Parlotype when I sign in to Windows</summary>
    public static string Settings_Startup_ToggleOn => Localizer.Lookup(nameof(Settings_Startup_ToggleOn));

    /// <summary>A single entry under your own user account (HKCU Run), pointing at Parlotype. No service, no scheduled task, no admin...</summary>
    public static string Settings_Startup_WhatChangesBody => Localizer.Lookup(nameof(Settings_Startup_WhatChangesBody));

    /// <summary>What this changes</summary>
    public static string Settings_Startup_WhatChangesHeading => Localizer.Lookup(nameof(Settings_Startup_WhatChangesHeading));

    /// <summary>Dark</summary>
    public static string Settings_Theme_Dark => Localizer.Lookup(nameof(Settings_Theme_Dark));

    /// <summary>Default (system)</summary>
    public static string Settings_Theme_Default => Localizer.Lookup(nameof(Settings_Theme_Default));

    /// <summary>Choose between system, light, or dark appearance.</summary>
    public static string Settings_Theme_Description => Localizer.Lookup(nameof(Settings_Theme_Description));

    /// <summary>Light</summary>
    public static string Settings_Theme_Light => Localizer.Lookup(nameof(Settings_Theme_Light));

    /// <summary>Theme</summary>
    public static string Settings_Theme_Title => Localizer.Lookup(nameof(Settings_Theme_Title));

    /// <summary>When on, Parlotype checks shortly after launch and every 6 hours after that.</summary>
    public static string Settings_Updates_CadenceNote => Localizer.Lookup(nameof(Settings_Updates_CadenceNote));

    /// <summary>Check now</summary>
    public static string Settings_Updates_CheckNowButton => Localizer.Lookup(nameof(Settings_Updates_CheckNowButton));

    /// <summary>Parlotype can check GitHub for new releases, download them in the background, and install them when you quit.</summary>
    public static string Settings_Updates_Description => Localizer.Lookup(nameof(Settings_Updates_Description));

    /// <summary>development build</summary>
    public static string Settings_Updates_DevelopmentBuild => Localizer.Lookup(nameof(Settings_Updates_DevelopmentBuild));

    /// <summary>Install and restart now</summary>
    public static string Settings_Updates_InstallAndRestartButton => Localizer.Lookup(nameof(Settings_Updates_InstallAndRestartButton));

    /// <summary>Installed version:</summary>
    public static string Settings_Updates_InstalledVersionLabel => Localizer.Lookup(nameof(Settings_Updates_InstalledVersionLabel));

    /// <summary>Last checked:</summary>
    public static string Settings_Updates_LastCheckedLabel => Localizer.Lookup(nameof(Settings_Updates_LastCheckedLabel));

    /// <summary>Never</summary>
    public static string Settings_Updates_Never => Localizer.Lookup(nameof(Settings_Updates_Never));

    /// <summary>Version {0} is available.</summary>
    public static string Settings_Updates_Status_AvailableFormat => Localizer.Lookup(nameof(Settings_Updates_Status_AvailableFormat));
    /// <summary>Version {0} is available.</summary>
    public static string Format_Settings_Updates_Status_AvailableFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Updates_Status_AvailableFormat, arg0);

    /// <summary>Checking for updates…</summary>
    public static string Settings_Updates_Status_Checking => Localizer.Lookup(nameof(Settings_Updates_Status_Checking));

    /// <summary>Downloading version {0}…</summary>
    public static string Settings_Updates_Status_DownloadingFormat => Localizer.Lookup(nameof(Settings_Updates_Status_DownloadingFormat));
    /// <summary>Downloading version {0}…</summary>
    public static string Format_Settings_Updates_Status_DownloadingFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Updates_Status_DownloadingFormat, arg0);

    /// <summary>The update check failed.</summary>
    public static string Settings_Updates_Status_Failed => Localizer.Lookup(nameof(Settings_Updates_Status_Failed));

    /// <summary>Not checked yet.</summary>
    public static string Settings_Updates_Status_NotChecked => Localizer.Lookup(nameof(Settings_Updates_Status_NotChecked));

    /// <summary>This build cannot update itself — it was not installed from Setup.exe.</summary>
    public static string Settings_Updates_Status_NotInstalled => Localizer.Lookup(nameof(Settings_Updates_Status_NotInstalled));

    /// <summary>Version {0} is downloaded. It installs when you quit Parlotype.</summary>
    public static string Settings_Updates_Status_ReadyFormat => Localizer.Lookup(nameof(Settings_Updates_Status_ReadyFormat));
    /// <summary>Version {0} is downloaded. It installs when you quit Parlotype.</summary>
    public static string Format_Settings_Updates_Status_ReadyFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Settings_Updates_Status_ReadyFormat, arg0);

    /// <summary>Parlotype is up to date.</summary>
    public static string Settings_Updates_Status_UpToDate => Localizer.Lookup(nameof(Settings_Updates_Status_UpToDate));

    /// <summary>Updates</summary>
    public static string Settings_Updates_Title => Localizer.Lookup(nameof(Settings_Updates_Title));

    /// <summary>Automatic update checks off</summary>
    public static string Settings_Updates_ToggleOff => Localizer.Lookup(nameof(Settings_Updates_ToggleOff));

    /// <summary>Check for updates automatically</summary>
    public static string Settings_Updates_ToggleOn => Localizer.Lookup(nameof(Settings_Updates_ToggleOn));

    /// <summary>An anonymous request to api.github.com for the public list of Parlotype releases, and a download of the release file ...</summary>
    public static string Settings_Updates_WhatSendsBody => Localizer.Lookup(nameof(Settings_Updates_WhatSendsBody));

    /// <summary>What this sends</summary>
    public static string Settings_Updates_WhatSendsHeading => Localizer.Lookup(nameof(Settings_Updates_WhatSendsHeading));

    /// <summary>Larger models are more accurate but use more disk and CPU/GPU.</summary>
    public static string Settings_WhisperModel_Description => Localizer.Lookup(nameof(Settings_WhisperModel_Description));

    /// <summary>Whisper Model</summary>
    public static string Settings_WhisperModel_Heading => Localizer.Lookup(nameof(Settings_WhisperModel_Heading));

    /// <summary>(not downloaded)</summary>
    public static string Settings_WhisperModel_NotDownloaded => Localizer.Lookup(nameof(Settings_WhisperModel_NotDownloaded));

    /// <summary>no translation</summary>
    public static string Settings_WhisperModel_NoTranslationBadge => Localizer.Lookup(nameof(Settings_WhisperModel_NoTranslationBadge));

    /// <summary>Transcription only — translating to English needs a multilingual model</summary>
    public static string Settings_WhisperModel_NoTranslationTooltip => Localizer.Lookup(nameof(Settings_WhisperModel_NoTranslationTooltip));

    /// <summary>Whisper model</summary>
    public static string Settings_WhisperModel_Title => Localizer.Lookup(nameof(Settings_WhisperModel_Title));

    /// <summary>Output-shaping options specific to the Whisper engine.</summary>
    public static string Settings_WhisperOutput_Description => Localizer.Lookup(nameof(Settings_WhisperOutput_Description));

    /// <summary>When enabled, recognized profanity is replaced with asterisks.</summary>
    public static string Settings_WhisperOutput_ProfanityNote => Localizer.Lookup(nameof(Settings_WhisperOutput_ProfanityNote));

    /// <summary>Profanity filter off</summary>
    public static string Settings_WhisperOutput_ProfanityOff => Localizer.Lookup(nameof(Settings_WhisperOutput_ProfanityOff));

    /// <summary>Profanity masked with ****</summary>
    public static string Settings_WhisperOutput_ProfanityOn => Localizer.Lookup(nameof(Settings_WhisperOutput_ProfanityOn));

    /// <summary>When enabled, transcription includes commas, periods, and other punctuation.</summary>
    public static string Settings_WhisperOutput_PunctuationNote => Localizer.Lookup(nameof(Settings_WhisperOutput_PunctuationNote));

    /// <summary>Punctuation stripped from output</summary>
    public static string Settings_WhisperOutput_PunctuationOff => Localizer.Lookup(nameof(Settings_WhisperOutput_PunctuationOff));

    /// <summary>Punctuation included in output</summary>
    public static string Settings_WhisperOutput_PunctuationOn => Localizer.Lookup(nameof(Settings_WhisperOutput_PunctuationOn));

    /// <summary>Whisper output</summary>
    public static string Settings_WhisperOutput_Title => Localizer.Lookup(nameof(Settings_WhisperOutput_Title));

    /// <summary>Whisper runtime</summary>
    public static string Settings_WhisperRuntime_Title => Localizer.Lookup(nameof(Settings_WhisperRuntime_Title));

    /// <summary>Parlotype — Settings</summary>
    public static string Settings_WindowTitle => Localizer.Lookup(nameof(Settings_WindowTitle));

    /// <summary>Cloud</summary>
    public static string Transcribe_CloudBadge => Localizer.Lookup(nameof(Transcribe_CloudBadge));

    /// <summary>Cloud: OpenAI-compatible</summary>
    public static string Transcribe_CloudProvider_OpenAiCompatible => Localizer.Lookup(nameof(Transcribe_CloudProvider_OpenAiCompatible));

    /// <summary>Cloud: xAI Grok</summary>
    public static string Transcribe_CloudProvider_XaiGrok => Localizer.Lookup(nameof(Transcribe_CloudProvider_XaiGrok));

    /// <summary>Hide window</summary>
    public static string Transcribe_HideWindowTooltip => Localizer.Lookup(nameof(Transcribe_HideWindowTooltip));

    /// <summary>Settings →</summary>
    public static string Transcribe_OpenSettingsLink => Localizer.Lookup(nameof(Transcribe_OpenSettingsLink));

    /// <summary>Settings</summary>
    public static string Transcribe_SettingsTooltip => Localizer.Lookup(nameof(Transcribe_SettingsTooltip));

    /// <summary>Auto</summary>
    public static string Transcribe_Source_Auto => Localizer.Lookup(nameof(Transcribe_Source_Auto));

    /// <summary>Keyboard</summary>
    public static string Transcribe_Source_Keyboard => Localizer.Lookup(nameof(Transcribe_Source_Keyboard));

    /// <summary>Cancelled</summary>
    public static string Transcribe_Status_Cancelled => Localizer.Lookup(nameof(Transcribe_Status_Cancelled));

    /// <summary>Cloud transcription failed</summary>
    public static string Transcribe_Status_CloudFailed => Localizer.Lookup(nameof(Transcribe_Status_CloudFailed));

    /// <summary>Cloud API key rejected — check Settings</summary>
    public static string Transcribe_Status_CloudKeyRejected => Localizer.Lookup(nameof(Transcribe_Status_CloudKeyRejected));

    /// <summary>Cloud provider not configured</summary>
    public static string Transcribe_Status_CloudNotConfigured => Localizer.Lookup(nameof(Transcribe_Status_CloudNotConfigured));

    /// <summary>Cloud provider unavailable — try again shortly</summary>
    public static string Transcribe_Status_CloudProviderUnavailable => Localizer.Lookup(nameof(Transcribe_Status_CloudProviderUnavailable));

    /// <summary>Cloud quota exceeded — check plan &amp; billing</summary>
    public static string Transcribe_Status_CloudQuotaExceeded => Localizer.Lookup(nameof(Transcribe_Status_CloudQuotaExceeded));

    /// <summary>Cloud rate limit reached — try again shortly</summary>
    public static string Transcribe_Status_CloudRateLimited => Localizer.Lookup(nameof(Transcribe_Status_CloudRateLimited));

    /// <summary>Loading model...</summary>
    public static string Transcribe_Status_LoadingModel => Localizer.Lookup(nameof(Transcribe_Status_LoadingModel));

    /// <summary>Ready</summary>
    public static string Transcribe_Status_Ready => Localizer.Lookup(nameof(Transcribe_Status_Ready));

    /// <summary>Recording...</summary>
    public static string Transcribe_Status_Recording => Localizer.Lookup(nameof(Transcribe_Status_Recording));

    /// <summary>Restart Parlotype to use the {0} runtime</summary>
    public static string Transcribe_Status_RuntimeRestartRequiredFormat => Localizer.Lookup(nameof(Transcribe_Status_RuntimeRestartRequiredFormat));
    /// <summary>Restart Parlotype to use the {0} runtime</summary>
    public static string Format_Transcribe_Status_RuntimeRestartRequiredFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Transcribe_Status_RuntimeRestartRequiredFormat, arg0);

    /// <summary>{0} runtime not available — change in Settings</summary>
    public static string Transcribe_Status_RuntimeUnavailableFormat => Localizer.Lookup(nameof(Transcribe_Status_RuntimeUnavailableFormat));
    /// <summary>{0} runtime not available — change in Settings</summary>
    public static string Format_Transcribe_Status_RuntimeUnavailableFormat(object? arg0) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Transcribe_Status_RuntimeUnavailableFormat, arg0);

    /// <summary>Translate to</summary>
    public static string Transcribe_TargetPicker_Header => Localizer.Lookup(nameof(Transcribe_TargetPicker_Header));

    /// <summary>Off — no translation</summary>
    public static string Transcribe_TargetPicker_Off => Localizer.Lookup(nameof(Transcribe_TargetPicker_Off));

    /// <summary>Parlotype — Transcribe</summary>
    public static string Transcribe_WindowTitle => Localizer.Lookup(nameof(Transcribe_WindowTitle));

    /// <summary>You speak</summary>
    public static string Transcribe_YouSpeakLabel => Localizer.Lookup(nameof(Transcribe_YouSpeakLabel));

    /// <summary>Exit</summary>
    public static string Tray_Exit => Localizer.Lookup(nameof(Tray_Exit));

    /// <summary>Open</summary>
    public static string Tray_Open => Localizer.Lookup(nameof(Tray_Open));

    /// <summary>Settings</summary>
    public static string Tray_Settings => Localizer.Lookup(nameof(Tray_Settings));
}
