<#
.SYNOPSIS
    Regenerates Strings.cs from Strings.resx (ADR-064).

.DESCRIPTION
    Strings.cs is a hand-shaped accessor that ADR-056 wrote by hand to keep the CLI
    build deterministic under TreatWarningsAsErrors. That held at 30 keys and does
    not hold at several hundred, so the file is now generated by this script and
    checked in — the determinism argument is satisfied by the output being a
    reviewed artefact in git, not by a designer running on someone's machine.

    Keys whose value contains a {0} placeholder get a Format_<key>(...) method with
    one parameter per distinct placeholder index, so a call site that passes the
    wrong number of arguments fails to compile instead of throwing FormatException
    in front of a user.

    LocalizationParityTests asserts the checked-in file matches what this produces,
    so forgetting to run it fails the build rather than going unnoticed.

.EXAMPLE
    pwsh scripts/gen-strings.ps1
#>
[CmdletBinding()]
param(
    # Verify only: exit 1 if the checked-in file is stale, and write nothing.
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$resxPath = Join-Path $repoRoot 'src/Parlotype.Desktop/Resources/Strings.resx'
$outPath = Join-Path $repoRoot 'src/Parlotype.Desktop/Resources/Strings.cs'

[xml]$resx = Get-Content -Path $resxPath -Raw -Encoding UTF8

$entries = @($resx.root.data | Where-Object { $null -ne $_.name } | Sort-Object { $_.name })
if ($entries.Count -eq 0) {
    throw "No <data> entries found in $resxPath"
}

$builder = [System.Text.StringBuilder]::new()
$null = $builder.AppendLine(@'
// <auto-generated>
//     Generated by scripts/gen-strings.ps1 from Strings.resx (ADR-064).
//     Do not edit by hand — add the key to Strings.resx and rerun the script.
// </auto-generated>

// The <auto-generated> header above opts this file out of the project's implicit
// nullable context, so the annotations below need it back explicitly (CS8669).
#nullable enable

namespace Parlotype.Desktop.Resources;

/// <summary>
/// Strongly-typed accessor for <c>Strings.resx</c> — the app's externalized
/// user-facing copy (ADR-056, ADR-064). Each property reads at the current
/// interface language, so a value captured before a language switch is stale;
/// bind through <see cref="Localizer.Entry"/> (or <c>{loc:Tr}</c> in markup) for
/// text that stays on screen. A missing key falls back to the key name so a stale
/// resx never crashes the UI. Public so tests can verify every key resolves
/// (Desktop has no InternalsVisibleTo for the test project's benefit here).
/// </summary>
public static class Strings
{
'@)

$first = $true
foreach ($entry in $entries) {
    $name = $entry.name
    $value = [string]$entry.value

    if (-not $first) { $null = $builder.AppendLine() }
    $first = $false

    # Escape the resx text for an XML doc comment so the sample stays readable in
    # IntelliSense without breaking the compiler's XML parser.
    $summary = $value -replace '&', '&amp;' -replace '<', '&lt;' -replace '>', '&gt;'
    $summary = ($summary -split "`r?`n") -join ' '
    if ($summary.Length -gt 120) { $summary = $summary.Substring(0, 117) + '...' }

    $null = $builder.AppendLine("    /// <summary>$summary</summary>")
    $null = $builder.AppendLine("    public static string $name => Localizer.Lookup(nameof($name));")

    # Composite format keys get a typed Format_ helper.
    $indexes = [regex]::Matches($value, '\{(\d+)') |
        ForEach-Object { [int]$_.Groups[1].Value } |
        Sort-Object -Unique

    if ($indexes.Count -gt 0) {
        $expected = 0..($indexes.Count - 1)
        if (Compare-Object $indexes $expected) {
            throw "Key '$name' has non-contiguous placeholders ($($indexes -join ', ')). Number them from {0} with no gaps."
        }

        $params = ($indexes | ForEach-Object { "object? arg$_" }) -join ', '
        $args = ($indexes | ForEach-Object { "arg$_" }) -join ', '

        $null = $builder.AppendLine("    /// <summary>$summary</summary>")
        $null = $builder.AppendLine("    public static string Format_$name($params) =>")
        $null = $builder.AppendLine("        string.Format(System.Globalization.CultureInfo.CurrentCulture, $name, $args);")
    }
}

$null = $builder.AppendLine('}')

# LF endings and a UTF-8 BOM: matches what the repo already has on disk, so the
# -Check comparison is about content rather than line-ending noise.
$generated = $builder.ToString() -replace "`r`n", "`n"

if ($Check) {
    $current = [System.IO.File]::ReadAllText($outPath)
    $current = $current -replace "`r`n", "`n"
    if ($current -ne $generated) {
        Write-Error "Strings.cs is out of date. Run: pwsh scripts/gen-strings.ps1"
        exit 1
    }
    Write-Host "Strings.cs is up to date ($($entries.Count) keys)."
    exit 0
}

$utf8Bom = [System.Text.UTF8Encoding]::new($true)
[System.IO.File]::WriteAllText($outPath, $generated, $utf8Bom)
Write-Host "Wrote $outPath ($($entries.Count) keys)."
